/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;
import processing.core.PApplet;
import processing.core.PImage;
import processing.core.PFont;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;

class CellTest extends PApplet{
    @Test
    public void cellTest(){
      Cell c = new Cell(null, 4, 5);
      assertNotNull(c);
      assertEquals(c.getX(), 4);
      assertEquals(c.getY(), 5);
    }
    @Test
    public void fruitTest() {
      Fruit f = new Fruit(null, 4, 5);
      assertNotNull(f);
      assertEquals(f.getX(), 4);
      assertEquals(f.getY(), 5);
    }

    @Test
    public void superfruitTest() {
      SuperFruit f = new SuperFruit(null, 4, 5);
      assertNotNull(f);
      assertEquals(f.getX(), 4);
      assertEquals(f.getY(), 5);
    }
    @Test
    public void mapTest(){
      Map m = new Map(null, 4, 5);
      assertNotNull(m);
      assertEquals(m.getX(), 4);
      assertEquals(m.getY(), 5);
    }

}
