/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;
import processing.core.PApplet;
import processing.core.PImage;
import processing.core.PFont;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import java.io.File;
import java.util.Scanner;
import java.lang.Long;
import org.json.simple.JSONObject;
import org.json.simple.JSONArray;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import processing.core.PImage;
import processing.core.PApplet;


class SettingsTest {
    @Test
    public void constructSettings() {
        Settings classUnderTest = new Settings(null);
        assertNotNull(classUnderTest);
    }
    @Test
    public void readConfigTest() {
        Settings s = new Settings(null);
        s.configReader();
        assertEquals(s.getMapFile(), "map.txt");
        assertEquals(s.getLives(), 3);
        assertEquals(s.getSpeed(), 1);
        assertEquals(s.getFrightLen(), 10);
        // assertEquals(s.getModes(), "[7, 20, 7, 20, 5, 20, 5, 1000]");
    }
    @Test
    public void mapReaderTest() {
        Settings s = new Settings(null);
        s.configReader();
        s.mapReader();
        String[][] map = s.getMap();
        assertEquals(map[20][13], "p");
    }



}
