/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;
import processing.core.PApplet;
import processing.core.PImage;
import processing.core.PFont;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;

class WakaTest {
    @Test
    public void constructWaka() {
        Player classUnderTest = new Player(null, 10, 20, 1);
        assertNotNull(classUnderTest);
    }
    @Test
    public void getWaka() {
        Player p = new Player(null, 10, 20, 1);
        assertEquals(p.getX(), 10);
        assertEquals(p.getY(), 20);
        assertEquals(p.getSpeed(), 1);
    }

}
